### ISSUE TITLE
CAMERA FAILED TO SETUP

### ISSUE THREAD

**Issue by havvanurbozomeroglu** [stereolabs/zed-examples#528] opened 2023-01-04 17:51 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hi,

**the installation was completed successfully.**

```
_Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing 'ZED camera SDK by Stereolabs (Use 'sudo apt install zstd' if zstd is not found)'  100%  
Ubuntu version 20.04 detected. OK
To continue you have to accept the EULA. Accept  [Y/n] ?y
Installing...
Installation path: /usr/local/zed
[sudo] password for hnb: 
Checking CUDA version...
OK: Found CUDA 11.4
Do you want to also install the static version of the ZED SDK (AI module will still require libsl_ai.so) [Y/n] ?y
Do you want to install the AI module (required for Object detection and Neural Depth, recommended), cuDNN 8.4 and TensorRT 8.4 will be installed [Y/n] ?y
Install samples (recommended) [Y/n] ?y
Installation path: /usr/local/zed/samples/
Dependencies installation complete
Do you want to install the Python API (recommended) [Y/n] ?y
Please specify your python executable: python3
Requirement already satisfied: numpy in /home/hnb/.local/lib/python3.8/site-packages (1.24.1)
-> Downloading to '/tmp/selfgz15379'
Detected platform: 
	 linux_x86_64
	 Python 3.8
	 ZED SDK 3.8
-> Checking if https://download.stereolabs.com/zedsdk/3.8/whl/linux_x86_64/pyzed-3.8-cp38-cp38-linux_x86_64.whl exists and is available
-> Found ! Downloading python package into /tmp/selfgz15379/pyzed-3.8-cp38-cp38-linux_x86_64.whl
-> Installing necessary dependencies
Requirement already satisfied: numpy in /home/hnb/.local/lib/python3.8/site-packages (1.24.1)
Processing ./pyzed-3.8-cp38-cp38-linux_x86_64.whl
Collecting numpy>=1.13
  Using cached numpy-1.24.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting cython>=0.28
  Using cached Cython-0.29.32-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Installing collected packages: numpy, cython, pyzed
Successfully installed cython-0.29.32 numpy-1.24.1 pyzed-3.8
Done
  To install it later or on a different environment run : 
 python -m pip install --ignore-installed /tmp/selfgz15379/pyzed-3.8-cp38-cp38-linux_x86_64.whl
The ZED Python API was installed for 'python3', when using conda environement or virtualenv, the ZED Python API may need to be resetup to be available (using 'python /usr/local/zed/get_python_api.py')
Do you want to run the ZED Diagnostic to download all AI models [Y/n] ?n

ZED SDK installation complete !_
```
but the error I got when I ran the camera_control python file is as follows: 

```
Running...
Opening ZED Camera...
CAMERA FAILED TO SETUP
```

OS: Ubuntu 20.04.5 LTS
GPU: NVIDIA Corporation GM108M [GeForce 920MX] 
ZED SDK version: ZED SDK 3.8

`nvidia-smi`:
![nvidia](https://user-images.githubusercontent.com/59619952/210617518-f24d03f8-a7a0-4bbd-b882-25b0b0d39e1a.png)

`nvcc -V`:
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jun__2_19:15:15_PDT_2021
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0
`

i'm just learning about zed. what am I supposed to do?

### Steps to Reproduce

1.ı dont know
2.
3.
...

### Expected Result

i was waiting for the camera to turn on

### Actual Result

error: 
Running...
Opening ZED Camera...
CAMERA FAILED TO SETUP

### ZED Camera model

ZED2

### Environment

```shell
OS: Ubuntu 20.04.5 LTS
GPU: NVIDIA Corporation GM108M [GeForce 920MX]
ZED SDK version: ZED SDK 3.8
```

**Comment by Myzhar** [comment] 2023-01-04 19:25
Hi @havvanurbozomeroglu 
this is not a bug report, but a support request.
Please write an email to support@stereolabs.com and add the report file generated by the ZED Diagnostic tool.
I close the issue.

**Closed by Myzhar** 2023-01-04 19:25 UTC
Labels: bug_report
